version: "2.4"
services:
  counter-service:
    container_name: counter-service-exercise
    image: saadmarcelo/api_python
    volumes:
      - ./data:/data
    ports:
      - "80:8080"
    restart: always
    mem_limit: 256M
    cpus: 0.5
